# Generated by Django 3.2.4 on 2022-03-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='customer_message',
        ),
    ]
